#
# Account: rhui-dev IAM
# to use for EC2 REST APIs
#
# note.. that some ec2 commands require diffent variable names :(
#
ACCESS_KEY=
SECRET_KEY=
# For python-boto
export AWS_ACCESS_KEY_ID=${ACCESS_KEY}
export AWS_ACCESS_KEY=${ACCESS_KEY}
export AWS_SECRET_ACCESS_KEY=${SECRET_KEY}
export AWS_SECRET_KEY=${SECRET_KEY}
echo "Set \$AWS_ACCESS_KEY_ID & \$AWS_SECRET_ACCESS_KEY to  'whayutin' AWS account"

